#+TITLE: Library Project: Library Reserve Requests Form
#+DATE: [2014-02-05 Wed]

* Original Specification
** Current Forms
- Forms are accessed in the Faculty Portal (required login).
  The forms supplies a drop-down menu with the faculty member's courses for the semester.
- There are two forms, one for electronic reserves and one for "material" reserves which include books, DVDs, and other physical materials
- The Forms request dates, loan parameters, and bibliographic information (author, title, pages, etc.)
- Only one request at a time can be submitted.
  The form must be completed for each item and there is no prompt to indicate that the user wants to submit additional items for the same class.
- The user cannot attach documents. 
  Faculty members must indicate in the special instructions field that they will send files separately by email or deliver hard copies for scanning.
- Faculty members cannot view submitted requests or edit the form after submission.
- The submitter does not receive any confirmation of submission.
- Cheryl does not receive a notification when new submissions are available.
- Cheryl can print reserve requests by faculty member.
- Submissions go into a report generated by Cognos.
- The faculty member's name, ID number, and course number appear automatically in the submission received by Cheryl Colson.

** Desired Features
- One form for both material types items.
  Form would "ask" for the item type (E or M) and direct user to the fields (or provide correct form) required for that material type.
- The form should allow for multiple submissions for the same class without having to fill in all the information again. 
  If possible the date of submission should be added automatically.
- The form should allow attachments (pdf, Word, etc.)
- The forms must have required fields and an area for notes. 
  The field for course number should be limited to 10 characters (XXXXxxx.xx)
- The submitter should receive a confirmation email if possible and Cheryl should receive an email notification with new reserve requests are received
- The submitter should be able to view (or save/print) their submissions.
- Cheryl should be able to print reserve request lists sorted by course number or faculty member.
- Summary reports should include material type, faculty member name, and date range.


* Sparknotes Edition
** Current Forms
- Form accessed with faculty user login.
- faculty member's current courses in drop-down menu.
- Reserve form for Electronic and (physical) Materials.
- Request form has date, loan, and bibliographic fields.
- Cheryl can print reserve requests by faculty member.
- Submissions go into a report generated by Cognos.
- The faculty member's name, ID number, and course number appear automatically in the submission received by Cheryl Colson.

** Problems 
- Want multiple submissions
- Requests can only be submitted one at a time
- faculty user can't attach documents. (e.g. faculty member has PDF and wants a chapter printed out for class.)
- faculty user's cannot view submitted requests or edit the request after submission
- faculty user does not receive confirmation email after submission
- Cheryl does not receive notification when new submissions are available

** Desired Features
- Multiple Submissions
- Single form for both Electronic and Material types
- multiple submissions without repeated information fields.
- auto-fill date of submission
- allow for attachments (pdf, word, etc.)
- must have required fields and an area for notes.
- course number field limited to 10 characters
- email confirmation for submissions for faculty user and Cheryl
- faculty user should be able to view submitted requests
- Cheryl should be able to print reserve request lists sorted by course number or faculty member.
- Summary reports should include material type, faculty member name, and date range.
