* Software Design Document
See [[http://en.wikipedia.org/wiki/Software_design_document][the Wikipedia article]] for more information.

** Data Design
- structures that reside within the software. 
- Attributes and relationships between data objects dictate the choice of data structures.
- Using Wordpress and Gravity Forms
** Architecture Design
- uses information flowing characteristics, and maps them into the program structure. 
- The transformation mapping method is applied to exhibit distinct boundaries between incoming and outgoing data. 
- The data flow diagrams allocate control input, processing and output along three separate modules.
** Interface Design
- Internal Program Interface
- External Program Interface
- Human Program Interface
  - Improved site design
  - Straight-forward and less confusing
  - "Tab" system for easy tracking of multiple submissions
  - Submission Confirmation emails
** Procedural Design
- describes structured programming concepts using graphical, tabular and textual notations. 
- These design mediums enable the designer to represent procedural detail, that facilitates translation to code. 
- This blueprint for implementation forms the basis for all subsequent software engineering worked.
