* Software Design Document
See [[http://en.wikipedia.org/wiki/Software_design_document][the Wikipedia article]] for more information.

** LEMURS
- Library Electronic Material User Request Site
- Software Design Document

* Contents
- Introduction
- Data/Procedural
- Architecture Design
- Interface Design


** Introduction
- The Library Electronic Material User Request Site (LEMURS) is a new website that is separate from “Portal” for the library staff at St. Mary’s College of Maryland. The following documentation will include information on the design, functions, processes, and uses for the new website.
  - Purpose:
    - A new user-friendly website that allows teachers to easily reserve and upload requests for the library staff to execute.
  - Design:
    - The new website will have all of the functionality of the current version, along with new features in accordance to design specifications dictated by the library staff.
  - Abbreviations and Definitions:
    - LEMURS: Library Electronic Material User Request Site
    - SMCM: St. Mary’s College of Maryland
    - Electronic: used to denote one of the 2 categories of materials. This category includes visual and audio materials such as news recordings, or pdf’s and electronic journal sections.
    - Physical: used to denote one of the 2 categories of materials. This category includes sections from books, DVDs, etc…


** Data/Procedural Design
- Overview
  - Using Wordpress and various plug-ins, we will create a website that is separate from the current “Portal” request site that the SMCM staff user that will allow faculty members to reserve materials. These materials include electronic and physical. 
- Features
  - Current Features
    - Form accessed with faculty user login.
    - Faculty member’s current courses in drop-down menu.
    - Reserve form for Electronic and Physical materials.
    - Request form has date, loan, and bibliographic fields.
    - Library Staff can print reserve requests by faculty member.
    - Submissions go into a report generated by Cognos.
    - The faculty member’s name, ID number, and course number appear automatically in the submission received by Library Staff
  - Desired Features
    - Multiple Submissions
    - Single form for both Electronic and Physical material types
    - Multiple submissions without repeated information fields.
    - Auto-fill date of submission
    - Allow for attachments (pdf, word, etc.)
    - Must have required fields and an area for notes.
    - Course number field limited to 10 characters
    - Email confirmation for submissions for faculty user and Cheryl
    - Faculty user should be able to view submitted requests
    - Cheryl should be able to print reserve request lists sorted by course number or faculty member.
    - Summary reports should include material type, faculty member name, and date range.
  - Object
    - A website for faculty members to reserve electronic or physical materials.
    - Materials include items from the SMCM Library, requests from other libraries, and pdf's that users upload.
    - Allows Library staff to reserve/print desired materials more efficiently
  - Primary USers
    - Library
    - Faculty
  - Separation of Concerns/Recurring Styles
    - Organization/categorization of fields may be an issue
    - User-friendliness
    - Server Space
  - Conceptual Integrity
    - "Vision of the project"
    - Create a library request site that improves upon the previous Portal edition.
    - New edition should have all old functions and new functions mentioned in the SRS
    - Focus on following wants and haves from the original request list
  - Design
    - User login
    - Material/Electronic request form
    - enter item information to reserve
    - can upload pdf's
    -  email confirmation
** Architecture Design
- Performance Requirements
  - Input
    - user wants to reservae a material type
    - user fills in information for material
    - user attaches desired material
    - user submits request
  - Output
    - confirmation email to both parties.
    - library reserves item(s)
    - library prints/gathers item(s) for user
** Interface Design
- Internal Program Interface
  - Wordpress
  - Gravity Forms
- Human Program Interface
  - Improved site design
  - Straight-forward and less confusing
  - "Tab" system for easy tracking of multiple submissions
  - Submission Confirmation emails
- Use Cases and Scenarios
  - Users
    - System Under Design
        - SMCM IT Department
          - Can monitor site and edit site.
          - Update and maintainenance
      - Faculty Use
        - Faculty Members
          - Professors can visit this site to access a request form via Wordpress.
      - Administrative Use
        - Library Staff
          - Cheryl Colson (Library Staff Member) can review and fulfill faculty requests received through Wordpress.
    - Scenarios (from Use Case Document)
      - Normal Use
        - Faculty
          - User enters course number that they wish to reserve materials for.
          - User can request electronic or physical materials
          - User can upload pdf's to be reserved
          - User can have multiple submissions
          - User receives an email confirmation of submission
        - Library
          - User receives email confirmation of request
          - User fulfills request
          - User can view/print requests
      - Abnormal Use
        - User 1 is teaching a class in Film Studies this semester and needs a specific DVD that is not available on campus, and the same item is reserved by different professors for the same time slot.
        - User 1 has reserved an item for three days starting at noon on Tuesday, however, User 2 wants to reserve the same item for three hours the same day from 9-11. Will his reserve be possible?
        - User 1 forgot to fill out a required field before trying to check out.
        
        
