* Software Design Document
See [[http://en.wikipedia.org/wiki/Software_design_document][the Wikipedia article]] for more information.

** Data Design
- structures that reside within the software. 
- Attributes and relationships between data objects dictate the choice of data structures.
- Object
  - What actions is the object responsible for?
  - What information does this object share?
- Stakeholders
- Separation of Concerns
- Quality-driven
- Recurring Styles (addressing recurring concenrs)
- Conceptual Integrity
  - "Vision of the project"
  - Create a library request site that improves upon the previous Portal edition.
  - New edition should have all old functions and new functions mentioned in the SRS
** Architecture Design
- uses information flowing characteristics, and maps them into the program structure. 
- The transformation mapping method is applied to exhibit distinct boundaries between incoming and outgoing data. 
- The data flow diagrams allocate control input, processing and output along three separate modules.
  - 
** Interface Design
- Internal Program Interface
  - Wordpress
  - Gravity Forms
- Human Program Interface
  - Improved site design
  - Straight-forward and less confusing
  - "Tab" system for easy tracking of multiple submissions
  - Submission Confirmation emails
** Procedural Design
- describes structured programming concepts using graphical, tabular and textual notations. 
- These design mediums enable the designer to represent procedural detail, that facilitates translation to code. 
- This blueprint for implementation forms the basis for all subsequent software engineering worked.
