* Software Design Document
See [[http://en.wikipedia.org/wiki/Software_design_document][the Wikipedia article]] for more information.

** LIBCORR
- Library Course Reserve Request
- Software Design Document

* Contents
- Introduction
- Data/Procedural Design
- Architecture Design
- Interface Design


** Introduction
- The Library Course Reserve Request (LIBCORR) is a new website that is separate from “Portal” for the Library staff at St. Mary’s College of Maryland. The following documentation will include information on the design, functions, processes, and uses for the new website.
  - Purpose:
    - A new user-friendly website that allows teachers to easily reserve and upload requests for the Library staff to execute.
  - Design:
    - Will allow Faculty to reserve either physical type or electronic type materials
    - Will allow Faculty to upload their own files for reserves
    - Will send Faculty and Library staff confimation emails
    - Will send the uploaded files to online database, able to be viewed by administrator/Library Staff
    - Will allow Faculty to add specific notes to their requests
    - Will allow Faculty to submit multiple requests in one submission
    - User Manual documenting proper use and scenarios will also be made accessible with the site
  - Abbreviations and Definitions:
    - LIBCORR: Library Course Reserve Request
    - SMCM: St. Mary’s College of Maryland
    - Electronic: used to denote one of the 2 categories of materials. This category includes visual and audio materials such as news recordings, or pdf’s and electronic journal sections.
    - Physical: used to denote one of the 2 categories of materials. This category includes sections from books, DVDs, etc…
    - User/Faculty/Member: refers to the SMCM Faculty who will be using this product for reserving materials.
    - Library/staff/Administrator: refers to the Library Staff who will be able to view and process reserves from Faculty members.


** Data/Procedural Design
- Overview
  - Using Wordpress, Gravity forms, and JQuerry we will create a website that is separate from the current “Portal” reserve site that the SMCM staff user that will allow Faculty members to reserve materials. These materials include electronic and physical items. 
- Features
  - Current Features
    - Form accessed with Faculty user login.
    - Faculty member’s current courses in drop-down menu.
    - Reserve form for Electronic and Physical materials.
    - Request form has date, loan, and bibliographic fields.
    - Library Staff can print reserve requests by Faculty member.
    - Submissions go into a report generated by Cognos.
    - The Faculty member’s name, ID number, and course number appear automatically in the submission received by Library Staff
  - Desired Features
    - Multiple Submissions
    - Single form for both Electronic and Physical material types
    - Multiple submissions without repeated information fields
    - Auto-fill date of submission
    - Allow for attachments (pdf, word, etc.)
    - Must have required fields and an area for notes
    - Course number field limited to 10 characters
    - Email confirmation for submissions for Faculty user and Cheryl
    - Faculty user should be able to view submitted requests
    - Cheryl should be able to print reserve request lists sorted by course number or Faculty member
    - Summary reports should include material type, Faculty member name, and date range
  - Object
    - A website for Faculty members to reserve electronic or physical materials
    - Allows Library staff to reserve/print desired materials more efficiently
    - Allow Faculty members to upload personal files to fill reserves
    - Allow Library Administrator to view, print, and remove previous reserves
  - Primary Users
    - Library
    - Faculty
  - Conceptual Integrity
    - "Vision of the project"
    - Create a library request site that improves upon the previous Portal edition.
    - New edition should have all old functions and new functions mentioned in the SRS
    - Focus on following wants and haves from the original request list
  - Design
    - User login
    - Material/Electronic item request form
    - Enter item's bibliographical information to reserve
    - Can upload pdf's with reserve submission
    - Email confirmation sent to Faculty and Library
    - Field for specific notes on reserves
    - Allows Library to see, print, and delete previous submissions
    - Allows for mutiple reservations for one submission
    
** Architecture Design
- Performance Requirements
  - Input
    - User wants to reserve a material type
    - User fills in bibliographical information for material
    - User attaches desired material (if applicable)
    - User submits request for item(s)
  - Output
    - Confirmation email to both parties.
    - Library reserves item(s)
    - Library prints/gathers item(s) for user
** Interface Design
- Internal Program Interface
  - Wordpress
  - Gravity Forms
  - JQuerry
- Human-Program Interface
  - Improved site design
  - Straight-forward and less confusing
  - "Tab" system for easy tracking of multiple submissions
  - Submission Confirmation emails
    - Faculty User
    - Library Staff
- Use Cases and Scenarios
  - Users
    - System Under Design
      - SMCM IT Department
        - Can monitor site and edit site.
        - Update and maintainenance
      - Faculty Use
        - Faculty Members
          - Professors can visit this site to access a request form via Wordpress.
      - Administrative Use
        - Library Staff
          - Cheryl Colson (Library Staff Member) can review and fulfill Faculty requests received through Wordpress.
    - Scenarios (from Use Case Document)
      - Normal Use
        - Faculty
          - User enters course number that they wish to reserve materials for.
          - User can request electronic or physical materials
          - User can upload pdf's to be reserved
          - User can have multiple submissions
          - User receives an email confirmation of submission
          - User can add specific notes for their requests
        - Library
          - User receives email confirmation of request
          - User fulfills request
          - User can view/print requests
      - Abnormal Use
        - User 1 is teaching a class in Film Studies this semester and needs a specific DVD that is not available on campus, and the same item is reserved by different professors for the same time slot.
        - User 1 has reserved an item for three days starting at noon on Tuesday, however, User 2 wants to reserve the same item for three hours the same day from 9-11. Will his reserve be possible?
        - User 1 forgot to fill out a required field before trying to check out.
        
        
