#+TITLE: Software Requirements Specification: Library Reserve Requests Form
#+DATE: [2014-02-05 Wed]

* Introduction
** Purpose
- To create a new library request site that improves upon the functionality of the previous portal edition.
** Definitions
- will, shall, must :: indicates mandatory software requirements
- should, may :: indicates optional software requirements
** System Overview
Within the context of the entire campus moving to a Wordpress-powered
system, this software solution maintains a reserve request form
powered by the [[http://www.gravityforms.com][Gravity Forms]] plugin.  Users (the faculty and staff of
SMC) will log in to the Wordpress form using their Google-provided
OpenID, complete the form, optionally upload any necessary
attachments, and submit the form for review and fulfillment, at which
point an email confirmation is sent as a receipt.
** References
- [[link to original requirements document]]
- [[link to homepage of whichever forms plugin we are using]]
- etc...
* Overall Description
** Product Perspective
*** Software Interfaces
Logical interfaces to other systems; likely nil
*** User Interfaces
User interface---definitely should /not/ be nil
*** Communication Interfaces
Communication with other systems, eg. the database.
(This seems very similar to [[*Software Interfaces]];
  research may need to be done concerning the difference therein.)
** Product Functions
- Will allow user to reserve electronic materials as well as physical materials
- Will allow the user upload certain files they own to be distributed electronically
** User Characteristics
- Users should be limited to St. Marys faculty
** Constraints, Assumptions and Dependencies
- It is assumed that the Professors will know their course numbers and which course they correspond to
- It is assumed that Professors will know how long the books are if they are reserving specific pages from a book
(e.g. they should not ask for pages 112-115 from a 100 page book)
- It is assumed that the Professors will know the call number of the material they are tring to reserve
* Specific Requirements
- It must have all the functionality of the previous form
- The user should be able to request multiple submissions
** External Interface Requirements
** Functional Requirements
** Design Constraints
- The site will be coded using HTML
*** Standards Compliance
** Logical Database Requirement
** Software System Attributes
*** Reliability
- We are utilizing Gravity forms, which is a new and up to date plugin formatter
*** Availability
- The site will be available through a key word search
*** Security
- There are no security measures currently in place
- A google login can be added at a later date if nesseccary
*** Maintainability
- The site will be maintained by the IT depertment
*** Portability
- There will be no mobile specific site developed
- The site should be usable on any portable web browser
** Other Requirements
