#+TITLE: Software Requirements Specification: Library Reserve Requests Form
#+DATE: [2014-02-05 Wed]

* Introduction
** Purpose
- To create a new library request site that improves upon the functionality of the previous portal edition.
** Definitions
- will, shall, must :: indicates mandatory software requirements
- should, may :: indicates optional software requirements
** System Overview
Within the context of the entire campus moving to a Wordpress-powered
system, this software solution maintains a reserve request form
powered by the [[http://www.gravityforms.com][Gravity Forms]] plugin.  Users (the faculty and staff of
SMC) will log in to the Wordpress form using their Google-provided
OpenID, complete the form, optionally upload any necessary
attachments, and submit the form for review and fulfillment, at which
point an email confirmation is sent as a receipt.
** References
- [[link to original requirements document]]
- [[link to homepage of whichever forms plugin we are using]]
- etc...
* Overall Description
** Product Perspective
*** Software Interfaces
Logical interfaces to other systems; likely nil
*** User Interfaces
User interface---definitely should /not/ be nil
*** Communication Interfaces
Communication with other systems, eg. the database.
(This seems very similar to [[*Software Interfaces]];
  research may need to be done concerning the difference therein.)
** Product Functions
- Will allow user to reserve electronic materials as well as physical materials
- Will allow the user upload certain files they own to be distributed electronically
** User Characteristics
- The users of this site are the faculty reserving forms on the site, the library staff processing those forms, and the database accessing any uploaded files
** Constraints, Assumptions and Dependencies
- The website will require access to the internet to submit a form
- The website will require the user to input their own course number and section
- The website will require the user to know the library call number of the item they are trying to reserve
- It may not be accessable by all browsers (to be tested at a later date)
- The library will have to check the availability of the request outside of the website
- It is assumed that the Professors will know their course numbers and which course they correspond to
- It is assumed that Professors will know how long the books are if they are reserving specific pages from a book
(e.g. they should not ask for pages 112-115 from a 100 page book)
- It is assumed that the Professors will know the call number of the material they are tring to reserve
* Specific Requirements
- It must have all the functionality of the previous form
- The user should be able to request multiple submissions
** External Interface Requirements
- The user will be required to fill in all of the information on the first form, however the repeated information will autofill on the next form
- The website will interact with the database in sending files and recieving a list of former reserves
- The website will communicate with the emails of the professor reserving and the library staff sending a confirmation email to both
- The website will utilize wordpress and HTML, the user must have a browser the can run these programs
- The database will be linked to the site to allow for uploads from the user
** Functional Requirements
- The user will be able to search for the form from any search engine
- The user will be able to inclue multiple submissions
- The user will be able to upload their own files to the database
- The user will be able to view previous submissions
- The website will have space for the request dates, loan parameters and bibliographical information (author, title, pages...)
- The website will allow access to both types of forms (electronic and material)
- The website will send an email to the requester and the library staff
** Design Constraints
- The site will be coded using HTML
- THe database will have a limited amount of space that is being managed by a third party
*** Standards Compliance
** Logical Database Requirement
- The site will be able to take in a file from the user and save it to the database filed under which professor requested it
** Software System Attributes
*** Reliability
- We are utilizing Gravity forms, which is a new and up to date plugin formatter
- The site will reliably send the confirmation emails to the professors and library staff
- The site will reliably send the uploaded files to the database
*** Availability
- The site will be available through a key word search
*** Security
- There are no security measures currently in place
- A google login can be added at a later date if nesseccary
*** Maintainability
- The site will be maintained by the IT depertment
- The site will be easy to update and add features to
*** Portability
- There will be no mobile specific site developed
- The site should be usable on any portable web browser
** Other Requirements
