#+TITLE: User Manual: Library Reserve Request Form

* GENERAL INFORMATION

** System overview
- Libcore is a website that will allow the faculty of St. Mary's College of Maryland to reserve electronic or physical materials for their classes.  It will also allow the Library staff to view the submissions and respond to them (i.e. print, delete, or mark them as read).  This form will work with all browsers and devices.

* SYSTEM SUMMARY

** System Configuration
- The website works on all browsers and devices.  It requires internet access to reserve and upload files to the database.  It also requires internet access to check and edit the reserves in the database.  Files in the database will also be viewable on all browsers and devices.

** User Access Levels
- The site will be accessable to everyone, but the database of requests will only be available to the library staff with the administrator wordpress login.

** Contingincies
- In the case of a loss of internet, the request will not be saved or submited.

* GETTING STARTED

** Access
- The course can be found online at [[]].
- The faculty will then have to login to WordPress to gain access to the form.


** Home Page
- The site will consist of a single page that will dynamically change according to the desired reserve.  




* ADMIN INFO

** Access and Logging in
- The site can be found at [[]].
- The admin will have to login with the proper admin Wordpress login.

** Accessing the submissions
- From the Dashboard the admin will select the Submissions link in the lower middle box in the page, this will take the admin to the list of submissions from the faculty.
[[temp]]
- The admin is then able to select the specific form they would like to view.
[[temp]]

** Deleting submissions
- The admin is able to delete a submission by placing the mouse pointer over the submission and selecting the red "trash" button
[[temp]]
- The admin is also able to check the boxes next to the submissions and set the bulk action to "trash", then clicking apply to remove multiple submissions.
[[temp]]
- The removed submissions will be then moved to the trash section that can be found by selecting "Trash" button.
[[temp]]
[[temp]]
- In the trash section the admin can permanently remove the submission from the database by placing the mouse pointer over a submission and selecting "Delete Permanently".
[[temp]]
- The admin can also delete permantely by checking multiple submissions boxes and setting the bulk action to "delete permanently" and clicking apply.
[[temp]]

** Favoriting submissions
- The admin is able to favorite submissions by selecting the star next to the submission
[[temp]]
- The admin is also able to 

